# Generated by Django 5.2.6 on 2025-09-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Masculino'), ('female', 'Feminino'), ('other', 'Outro')], max_length=6, null=True, verbose_name='Gênero'),
        ),
    ]
