# Generated by Django 5.2.6 on 2025-09-23 12:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0002_alter_usuario_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_publico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('metodo', models.CharField(choices=[('pix', 'PIX')], default='pix', max_length=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('cancelado', 'Cancelado'), ('expirado', 'Expirado')], default='pendente', max_length=20)),
                ('pix_payload', models.TextField(blank=True)),
                ('pix_qr', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='academia.plano')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
