# Generated by Django 5.2.8 on 2025-11-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0003_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('professor', 'Professor'), ('aluno', 'Aluno')], default='aluno', max_length=20, verbose_name='Função'),
        ),
    ]
