# Generated by Django 5.2.8 on 2025-11-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0004_usuario_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='perimetro_braco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Perímetro Braço (cm)'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='perimetro_cintura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Perímetro Cintura (cm)'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='perimetro_coxa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Perímetro Coxa (cm)'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='perimetro_peito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Perímetro Peito (cm)'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='perimetro_quadril',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Perímetro Quadril (cm)'),
        ),
    ]
