# Generated by Django 5.2.8 on 2025-11-13 13:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0005_avaliacao_perimetro_braco_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaseTorneio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_fase', models.CharField(choices=[('oitavas', 'Oitavas de Final'), ('quartas', 'Quartas de Final'), ('semis', 'Semi-Final'), ('final', 'Final'), ('terceiro_lugar', 'Disputa de 3º Lugar')], max_length=20, verbose_name='Tipo de Fase')),
                ('numero_fase', models.IntegerField(default=1, verbose_name='Número da Fase')),
                ('data_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Data de Início')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fim')),
                ('concluida', models.BooleanField(default=False, verbose_name='Concluída')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Fase do Torneio',
                'verbose_name_plural': 'Fases do Torneio',
                'ordering': ['torneio', 'numero_fase'],
            },
        ),
        migrations.CreateModel(
            name='ExercicioFase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField(default=1, verbose_name='Ordem')),
                ('series', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Séries')),
                ('repeticoes', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Repetições')),
                ('peso_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso Mínimo (kg)')),
                ('peso_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso Máximo (kg)')),
                ('tempo_limite', models.IntegerField(blank=True, null=True, verbose_name='Tempo Limite (segundos)')),
                ('criterio_vitoria', models.CharField(blank=True, help_text='Ex: Maior número de repetições, Menor tempo, etc.', max_length=100, verbose_name='Critério de Vitória')),
                ('pontos', models.IntegerField(default=1, help_text='Pontos que este exercício vale na fase', verbose_name='Pontos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases_torneio', to='academia.exercicio')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='academia.fasetorneio')),
            ],
            options={
                'verbose_name': 'Exercício da Fase',
                'verbose_name_plural': 'Exercícios da Fase',
                'ordering': ['fase', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='ParticipanteTorneio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Inscrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('eliminado', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('posicao_final', models.IntegerField(blank=True, null=True, verbose_name='Posição Final')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes_torneios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participante do Torneio',
                'verbose_name_plural': 'Participantes do Torneio',
                'ordering': ['data_inscricao'],
            },
        ),
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_chave', models.IntegerField(default=1, verbose_name='Número da Chave')),
                ('data_partida', models.DateTimeField(blank=True, null=True, verbose_name='Data da Partida')),
                ('concluida', models.BooleanField(default=False, verbose_name='Concluída')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chaves', to='academia.fasetorneio')),
                ('participante1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chaves_como_participante1', to='academia.participantetorneio')),
                ('participante2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chaves_como_participante2', to='academia.participantetorneio')),
                ('vencedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chaves_vencidas', to='academia.participantetorneio')),
            ],
            options={
                'verbose_name': 'Chave',
                'verbose_name_plural': 'Chaves',
                'ordering': ['fase', 'numero_chave'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoPartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participante1_pontos', models.IntegerField(default=0, verbose_name='Pontos Participante 1')),
                ('participante2_pontos', models.IntegerField(default=0, verbose_name='Pontos Participante 2')),
                ('detalhes', models.JSONField(default=dict, help_text='Detalhes dos exercícios realizados por cada participante', verbose_name='Detalhes do Resultado')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro')),
                ('chave', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='academia.chave')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_registrados', to=settings.AUTH_USER_MODEL)),
                ('vencedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_vencedor', to='academia.participantetorneio')),
            ],
            options={
                'verbose_name': 'Resultado da Partida',
                'verbose_name_plural': 'Resultados das Partidas',
            },
        ),
        migrations.CreateModel(
            name='Torneio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Torneio')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_inicio_inscricoes', models.DateTimeField(verbose_name='Data de Início das Inscrições')),
                ('data_fim_inscricoes', models.DateTimeField(verbose_name='Data de Fim das Inscrições')),
                ('data_inicio', models.DateTimeField(verbose_name='Data de Início do Torneio')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fim do Torneio')),
                ('status', models.CharField(choices=[('inscricoes_abertas', 'Inscrições Abertas'), ('em_andamento', 'Em Andamento'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='inscricoes_abertas', max_length=20, verbose_name='Status')),
                ('max_participantes', models.IntegerField(default=16, verbose_name='Máximo de Participantes')),
                ('regras', models.TextField(blank=True, verbose_name='Regras do Torneio')),
                ('premio', models.TextField(blank=True, verbose_name='Prêmio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='torneios_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Torneio',
                'verbose_name_plural': 'Torneios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='participantetorneio',
            name='torneio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='academia.torneio'),
        ),
        migrations.AddField(
            model_name='fasetorneio',
            name='torneio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases', to='academia.torneio'),
        ),
        migrations.AlterUniqueTogether(
            name='participantetorneio',
            unique_together={('torneio', 'usuario')},
        ),
        migrations.AlterUniqueTogether(
            name='fasetorneio',
            unique_together={('torneio', 'tipo_fase')},
        ),
    ]
