# Generated by Django 5.2.8 on 2025-11-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0006_fasetorneio_exerciciofase_participantetorneio_chave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='mercado_pago_payment_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='mercado_pago_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pedido',
            name='mercado_pago_status_detail',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo',
            field=models.CharField(choices=[('pix', 'PIX'), ('cartao', 'Cartão de Crédito')], default='pix', max_length=10),
        ),
    ]
