# Generated by Django 5.2.8 on 2025-11-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0007_pedido_mercado_pago_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='is_subscription',
            field=models.BooleanField(default=False, verbose_name='É Assinatura'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='mercado_pago_subscription_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='mercado_pago_subscription_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pedido',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Fim da Assinatura'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='subscription_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início da Assinatura'),
        ),
    ]
