# Generated by Django 5.2.8 on 2025-11-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0008_pedido_is_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='mercado_pago_preference_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID da preferência do Checkout Pro', max_length=200, null=True),
        ),
    ]
