# Generated by Django 5.2.8 on 2025-11-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0009_pedido_mercado_pago_preference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cref',
            field=models.CharField(blank=True, help_text='Formato: 000000-G/UF', max_length=20, null=True, verbose_name='CREF'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='especialidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Especialidade'),
        ),
    ]
