# Generated by Django 5.2.8 on 2025-11-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0010_add_professor_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(blank=True, help_text='Formato: 000.000.000-00', max_length=14, null=True, verbose_name='CPF'),
        ),
    ]
